version: '3'

services:
  php:
    image: php:7.4-apache
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    expose:
      - 6379
    networks:
      static-network:
        ipv4_address: 192.168.230.5


networks:
  static-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.230.0/28
volumes:
  dbdata:

